development:
  host: localhost
  database: devise_mongoid_template_development

test:
  host: localhost
  database: devise_mongoid_template_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
